name: smart_asset_generator
description: A Dart package to generate Dart asset references with camelCase naming from your assets folder.
version: 0.0.10  # Increment version for new publish
homepage: https://github.com/developerdivyaraj/smart_asset_generator
repository: https://github.com/developerdivyaraj/smart_asset_generator

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Fix the executables section - both should match
executables:
  smart_asset_generator: smart_asset_generator

flutter: